# cargo-deny configuration for cyberkrill
# https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
# Path to the advisory database
db-path = "~/.cargo/advisory-db"
# The URL(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# How to handle crates with security vulnerabilities
version = 2
ignore = [
    # slab v0.4.10 vulnerability - will be fixed with cargo update
    "RUSTSEC-2025-0047",
]

[licenses]
# How to handle various licenses
version = 2
# Allow common open source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    "MPL-2.0",
    "Unlicense",
    "Zlib",
    "OpenSSL",
    "MITNFA",
    "GPL-3.0-or-later",
]
confidence-threshold = 0.8
# Ignore unlicensed crates from git dependencies
exceptions = [
    { allow = ["MIT"], name = "cktap-direct" },
    { allow = ["MIT"], name = "frozenkrill-core" },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "unescaper"
expression = "GPL-3.0-or-later OR MIT"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
# Multiple versions of the same crate allowed during transition periods
multiple-versions = "warn"
# Allow wildcard dependencies during development
wildcards = "allow"
highlight = "all"

# Deny specific crates
deny = [
    # Prefer rustls over openssl for better security
    { name = "openssl" },
    # Avoid C dependencies when possible
    { name = "cmake" },
]

[sources]
# Warn about crates from unknown registries
unknown-registry = "warn"
# Warn about git dependencies
unknown-git = "warn"
# Allow crates.io
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# Allow our git dependencies
allow-git = [
    "https://github.com/rust-bitcoin/rust-bip39",
    "https://github.com/douglaz/cktap-direct",
    "https://github.com/douglaz/rust-coldcard",
    "https://github.com/planktonlabs/frozenkrill",
    "https://github.com/douglaz/hidraw-rs",
    "https://github.com/trezor/trezor-firmware",
]