[build]
# Default to musl target for static builds
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
# Use the linker from the nix shell environment
linker = "x86_64-unknown-linux-musl-cc"
