name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Build with glibc and all features
      run: nix develop -c cargo build -F smartcards
    - name: Build with musl and only default features
      run: nix develop -c cargo build --target x86_64-unknown-linux-musl
    - name: Run tests with glibc and all features
      run: nix develop -c cargo test -F smartcards
    - name: Run tests with musl and only default features
      run: nix develop -c cargo test --target x86_64-unknown-linux-musl
