name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    # Only cache cargo registry (dependencies), not target directory
    # Target caching conflicts with nix environment and multiple build targets
    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-
    - name: Check formatting
      run: nix develop -c cargo fmt --check
    
    - name: Run linting
      run: nix develop -c cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Build default (all features)
      run: nix develop -c cargo build
    
    - name: Build minimal (no features)
      run: nix develop -c cargo build --no-default-features
    
    - name: Run tests (all features)
      run: nix develop -c cargo test
    
    - name: Run tests minimal (no features)
      run: nix develop -c cargo test --no-default-features
    
    - name: Build with nix (static musl binary)
      run: nix build
