name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-
    
    - name: Cache Cargo target directory
      uses: actions/cache@v4
      with:
        path: target/
        key: cargo-target-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
        restore-keys: |
          cargo-target-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-
          cargo-target-${{ runner.os }}-
    - name: Check formatting
      run: nix develop -c cargo fmt --check
    
    - name: Run linting
      run: nix develop -c cargo clippy -- -D warnings
    
    - name: Build with glibc and all features
      run: nix develop -c cargo build -F smartcards
    
    - name: Build with musl and only default features
      run: nix develop -c cargo build --target x86_64-unknown-linux-musl
    
    - name: Run tests with glibc and all features
      run: nix develop -c cargo test -F smartcards
    
    - name: Run tests with musl and only default features
      run: nix develop -c cargo test --target x86_64-unknown-linux-musl
